import sharedRulesJson from "../../shared/gameplay_rules.json";
import { CARD_POOL as CARD_POOL_FROM_CARD_RULES } from "./card_rules";

interface SharedRules {
  RULES_VERSION: number;
  ROOM_CODE_LENGTH: number;
  ROOM_CODE_ALPHABET: string;
  NICKNAME_MAX_LENGTH: number;
  BOARD_W: number;
  BOARD_H: number;
  STONE_COUNT_PER_PLAYER: number;
  STONE_RADIUS: number;
  PLACE_GAP_PX: number;
  NO_PLACE_BUFFER: number;
  PLACEMENT_REVEAL_SEC: number;
  CARD_PICK_SEC: number;
  TURN_TIME_LIMIT_SEC: number;
  SNAPSHOT_TIMEOUT_SEC: number;
  HOST_DEAL_COUNT: number;
  HOST_PICK_COUNT: number;
  GUEST_DEAL_COUNT: number;
  GUEST_PICK_COUNT: number;
  MAX_SHOT_POWER: number;
  POWER_PER_PIXEL: number;
  SHOT_SPEED_SCALE: number;
  PHYSICS_DAMPING_PER_SEC: number;
  PHYSICS_RESTITUTION: number;
  PHYSICS_STOP_SPEED: number;
  PHYSICS_FIXED_STEP_SEC: number;
  PHYSICS_MAX_SIM_SEC: number;
  ROCK_OBSTACLE_WIDTH: number;
  ROCK_OBSTACLE_HEIGHT: number;
  ROCK_OBSTACLE_MARGIN: number;
  SHOCKWAVE_RANGE_MULTIPLIER: number;
  SHOCKWAVE_STRENGTH: number;
  CHAT_MAX_LENGTH: number;
  CHAT_RATE_WINDOW_SEC: number;
  CHAT_RATE_MAX_MSG: number;
  CHAT_RATE_BURST: number;
}

const DEFAULT_SHARED_RULES: SharedRules = {
  RULES_VERSION: 1,
  ROOM_CODE_LENGTH: 16,
  ROOM_CODE_ALPHABET: "ABCDEFGHJKLMNPQRSTUVWXYZ23456789",
  NICKNAME_MAX_LENGTH: 20,
  BOARD_W: 600,
  BOARD_H: 600,
  STONE_COUNT_PER_PLAYER: 7,
  STONE_RADIUS: 14,
  PLACE_GAP_PX: 5,
  NO_PLACE_BUFFER: 19,
  PLACEMENT_REVEAL_SEC: 5,
  CARD_PICK_SEC: 15,
  TURN_TIME_LIMIT_SEC: 30,
  SNAPSHOT_TIMEOUT_SEC: 8,
  HOST_DEAL_COUNT: 2,
  HOST_PICK_COUNT: 1,
  GUEST_DEAL_COUNT: 3,
  GUEST_PICK_COUNT: 2,
  MAX_SHOT_POWER: 900,
  POWER_PER_PIXEL: 4,
  SHOT_SPEED_SCALE: 0.6,
  PHYSICS_DAMPING_PER_SEC: 2.4,
  PHYSICS_RESTITUTION: 0.86,
  PHYSICS_STOP_SPEED: 12,
  PHYSICS_FIXED_STEP_SEC: 0.016,
  PHYSICS_MAX_SIM_SEC: 6,
  ROCK_OBSTACLE_WIDTH: 100,
  ROCK_OBSTACLE_HEIGHT: 50,
  ROCK_OBSTACLE_MARGIN: 5,
  SHOCKWAVE_RANGE_MULTIPLIER: 4,
  SHOCKWAVE_STRENGTH: 200,
  CHAT_MAX_LENGTH: 120,
  CHAT_RATE_WINDOW_SEC: 10,
  CHAT_RATE_MAX_MSG: 6,
  CHAT_RATE_BURST: 2
};

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function readNumberRule(source: Record<string, unknown>, key: string, fallback: number): number {
  const value = source[key];
  return isFiniteNumber(value) ? value : fallback;
}

function readStringRule(source: Record<string, unknown>, key: string, fallback: string): string {
  const value = source[key];
  return typeof value === "string" && value.length > 0 ? value : fallback;
}

function sanitizeSharedRules(raw: unknown): SharedRules {
  const source = raw && typeof raw === "object" ? (raw as Record<string, unknown>) : {};

  return {
    RULES_VERSION: readNumberRule(source, "RULES_VERSION", DEFAULT_SHARED_RULES.RULES_VERSION),
    ROOM_CODE_LENGTH: readNumberRule(source, "ROOM_CODE_LENGTH", DEFAULT_SHARED_RULES.ROOM_CODE_LENGTH),
    ROOM_CODE_ALPHABET: readStringRule(source, "ROOM_CODE_ALPHABET", DEFAULT_SHARED_RULES.ROOM_CODE_ALPHABET),
    NICKNAME_MAX_LENGTH: readNumberRule(source, "NICKNAME_MAX_LENGTH", DEFAULT_SHARED_RULES.NICKNAME_MAX_LENGTH),
    BOARD_W: readNumberRule(source, "BOARD_W", DEFAULT_SHARED_RULES.BOARD_W),
    BOARD_H: readNumberRule(source, "BOARD_H", DEFAULT_SHARED_RULES.BOARD_H),
    STONE_COUNT_PER_PLAYER: readNumberRule(source, "STONE_COUNT_PER_PLAYER", DEFAULT_SHARED_RULES.STONE_COUNT_PER_PLAYER),
    STONE_RADIUS: readNumberRule(source, "STONE_RADIUS", DEFAULT_SHARED_RULES.STONE_RADIUS),
    PLACE_GAP_PX: readNumberRule(source, "PLACE_GAP_PX", DEFAULT_SHARED_RULES.PLACE_GAP_PX),
    NO_PLACE_BUFFER: readNumberRule(source, "NO_PLACE_BUFFER", DEFAULT_SHARED_RULES.NO_PLACE_BUFFER),
    PLACEMENT_REVEAL_SEC: readNumberRule(source, "PLACEMENT_REVEAL_SEC", DEFAULT_SHARED_RULES.PLACEMENT_REVEAL_SEC),
    CARD_PICK_SEC: readNumberRule(source, "CARD_PICK_SEC", DEFAULT_SHARED_RULES.CARD_PICK_SEC),
    TURN_TIME_LIMIT_SEC: readNumberRule(source, "TURN_TIME_LIMIT_SEC", DEFAULT_SHARED_RULES.TURN_TIME_LIMIT_SEC),
    SNAPSHOT_TIMEOUT_SEC: readNumberRule(source, "SNAPSHOT_TIMEOUT_SEC", DEFAULT_SHARED_RULES.SNAPSHOT_TIMEOUT_SEC),
    HOST_DEAL_COUNT: readNumberRule(source, "HOST_DEAL_COUNT", DEFAULT_SHARED_RULES.HOST_DEAL_COUNT),
    HOST_PICK_COUNT: readNumberRule(source, "HOST_PICK_COUNT", DEFAULT_SHARED_RULES.HOST_PICK_COUNT),
    GUEST_DEAL_COUNT: readNumberRule(source, "GUEST_DEAL_COUNT", DEFAULT_SHARED_RULES.GUEST_DEAL_COUNT),
    GUEST_PICK_COUNT: readNumberRule(source, "GUEST_PICK_COUNT", DEFAULT_SHARED_RULES.GUEST_PICK_COUNT),
    MAX_SHOT_POWER: readNumberRule(source, "MAX_SHOT_POWER", DEFAULT_SHARED_RULES.MAX_SHOT_POWER),
    POWER_PER_PIXEL: readNumberRule(source, "POWER_PER_PIXEL", DEFAULT_SHARED_RULES.POWER_PER_PIXEL),
    SHOT_SPEED_SCALE: readNumberRule(source, "SHOT_SPEED_SCALE", DEFAULT_SHARED_RULES.SHOT_SPEED_SCALE),
    PHYSICS_DAMPING_PER_SEC: readNumberRule(source, "PHYSICS_DAMPING_PER_SEC", DEFAULT_SHARED_RULES.PHYSICS_DAMPING_PER_SEC),
    PHYSICS_RESTITUTION: readNumberRule(source, "PHYSICS_RESTITUTION", DEFAULT_SHARED_RULES.PHYSICS_RESTITUTION),
    PHYSICS_STOP_SPEED: readNumberRule(source, "PHYSICS_STOP_SPEED", DEFAULT_SHARED_RULES.PHYSICS_STOP_SPEED),
    PHYSICS_FIXED_STEP_SEC: readNumberRule(source, "PHYSICS_FIXED_STEP_SEC", DEFAULT_SHARED_RULES.PHYSICS_FIXED_STEP_SEC),
    PHYSICS_MAX_SIM_SEC: readNumberRule(source, "PHYSICS_MAX_SIM_SEC", DEFAULT_SHARED_RULES.PHYSICS_MAX_SIM_SEC),
    ROCK_OBSTACLE_WIDTH: readNumberRule(source, "ROCK_OBSTACLE_WIDTH", DEFAULT_SHARED_RULES.ROCK_OBSTACLE_WIDTH),
    ROCK_OBSTACLE_HEIGHT: readNumberRule(source, "ROCK_OBSTACLE_HEIGHT", DEFAULT_SHARED_RULES.ROCK_OBSTACLE_HEIGHT),
    ROCK_OBSTACLE_MARGIN: readNumberRule(source, "ROCK_OBSTACLE_MARGIN", DEFAULT_SHARED_RULES.ROCK_OBSTACLE_MARGIN),
    SHOCKWAVE_RANGE_MULTIPLIER: readNumberRule(source, "SHOCKWAVE_RANGE_MULTIPLIER", DEFAULT_SHARED_RULES.SHOCKWAVE_RANGE_MULTIPLIER),
    SHOCKWAVE_STRENGTH: readNumberRule(source, "SHOCKWAVE_STRENGTH", DEFAULT_SHARED_RULES.SHOCKWAVE_STRENGTH),
    CHAT_MAX_LENGTH: readNumberRule(source, "CHAT_MAX_LENGTH", DEFAULT_SHARED_RULES.CHAT_MAX_LENGTH),
    CHAT_RATE_WINDOW_SEC: readNumberRule(source, "CHAT_RATE_WINDOW_SEC", DEFAULT_SHARED_RULES.CHAT_RATE_WINDOW_SEC),
    CHAT_RATE_MAX_MSG: readNumberRule(source, "CHAT_RATE_MAX_MSG", DEFAULT_SHARED_RULES.CHAT_RATE_MAX_MSG),
    CHAT_RATE_BURST: readNumberRule(source, "CHAT_RATE_BURST", DEFAULT_SHARED_RULES.CHAT_RATE_BURST)
  };
}

const SHARED_RULES = sanitizeSharedRules(sharedRulesJson);

export const DEFAULT_PHASE = "WAITING";
export const PHASE_WAITING = "WAITING";
export const PHASE_TURN_ORDER = "TURN_ORDER";
export const PHASE_PLACEMENT_PRIVATE = "PLACEMENT_PRIVATE";
export const PHASE_PLACEMENT_REVEAL = "PLACEMENT_REVEAL";
export const PHASE_CARD_SELECT = "CARD_SELECT";
export const PHASE_PLAYING = "PLAYING";
export const PHASE_RESULT = "RESULT";

export const RULES_VERSION = SHARED_RULES.RULES_VERSION;

export const ROOM_CODE_LENGTH = SHARED_RULES.ROOM_CODE_LENGTH;
export const ROOM_CODE_ALPHABET = SHARED_RULES.ROOM_CODE_ALPHABET;

export const NICKNAME_MAX_LENGTH = SHARED_RULES.NICKNAME_MAX_LENGTH;

export const BOARD_W = SHARED_RULES.BOARD_W;
export const BOARD_H = SHARED_RULES.BOARD_H;
export const STONE_COUNT_PER_PLAYER = SHARED_RULES.STONE_COUNT_PER_PLAYER;
export const STONE_RADIUS = SHARED_RULES.STONE_RADIUS;
export const PLACE_GAP_PX = SHARED_RULES.PLACE_GAP_PX;
export const MIN_PLACE_DISTANCE = STONE_RADIUS + PLACE_GAP_PX;
export const NO_PLACE_BUFFER = SHARED_RULES.NO_PLACE_BUFFER;
export const PLACEMENT_REVEAL_SEC = SHARED_RULES.PLACEMENT_REVEAL_SEC;
export const CARD_PICK_SEC = SHARED_RULES.CARD_PICK_SEC;
export const TURN_TIME_LIMIT_SEC = SHARED_RULES.TURN_TIME_LIMIT_SEC;
export const SNAPSHOT_TIMEOUT_SEC = SHARED_RULES.SNAPSHOT_TIMEOUT_SEC;

export const CARD_POOL = [...CARD_POOL_FROM_CARD_RULES];
export type CardId = string;
export const HOST_DEAL_COUNT = SHARED_RULES.HOST_DEAL_COUNT;
export const HOST_PICK_COUNT = SHARED_RULES.HOST_PICK_COUNT;
export const GUEST_DEAL_COUNT = SHARED_RULES.GUEST_DEAL_COUNT;
export const GUEST_PICK_COUNT = SHARED_RULES.GUEST_PICK_COUNT;

// Base shot input tuning (all cards use this baseline).
export const MAX_SHOT_POWER = SHARED_RULES.MAX_SHOT_POWER;
export const POWER_PER_PIXEL = SHARED_RULES.POWER_PER_PIXEL;

// Simulation tuning shared with client physics.
export const SHOT_SPEED_SCALE = SHARED_RULES.SHOT_SPEED_SCALE;
export const PHYSICS_DAMPING_PER_SEC = SHARED_RULES.PHYSICS_DAMPING_PER_SEC;
export const PHYSICS_RESTITUTION = SHARED_RULES.PHYSICS_RESTITUTION;
export const PHYSICS_STOP_SPEED = SHARED_RULES.PHYSICS_STOP_SPEED;
export const PHYSICS_FIXED_STEP_SEC = SHARED_RULES.PHYSICS_FIXED_STEP_SEC;
export const PHYSICS_MAX_SIM_SEC = SHARED_RULES.PHYSICS_MAX_SIM_SEC;

// `rockfall` obstacle footprint/boundary allowance.
export const ROCK_OBSTACLE_WIDTH = SHARED_RULES.ROCK_OBSTACLE_WIDTH;
export const ROCK_OBSTACLE_HEIGHT = SHARED_RULES.ROCK_OBSTACLE_HEIGHT;
export const ROCK_OBSTACLE_MARGIN = SHARED_RULES.ROCK_OBSTACLE_MARGIN;

// `shockwave` tuning.
// - actual radius = STONE_RADIUS * SHOCKWAVE_RANGE_MULTIPLIER
// - SHOCKWAVE_STRENGTH is flat impulse (distance falloff disabled in current design)
export const SHOCKWAVE_RANGE_MULTIPLIER = SHARED_RULES.SHOCKWAVE_RANGE_MULTIPLIER;
export const SHOCKWAVE_STRENGTH = SHARED_RULES.SHOCKWAVE_STRENGTH;

export const CHAT_MAX_LENGTH = SHARED_RULES.CHAT_MAX_LENGTH;
export const CHAT_RATE_WINDOW_SEC = SHARED_RULES.CHAT_RATE_WINDOW_SEC;
export const CHAT_RATE_MAX_MSG = SHARED_RULES.CHAT_RATE_MAX_MSG;
export const CHAT_RATE_BURST = SHARED_RULES.CHAT_RATE_BURST;

export const CHAT_ALLOWED_PHASES = new Set<string>([
  PHASE_WAITING,
  PHASE_TURN_ORDER,
  PHASE_PLACEMENT_PRIVATE,
  PHASE_PLACEMENT_REVEAL,
  PHASE_CARD_SELECT,
  PHASE_PLAYING,
  PHASE_RESULT
]);
